### ISSUE TITLE
What is the unit of memory usage?

### ISSUE THREAD

**Issue by Hecbi** [hotchemi/LruCache#2]
i create a lruCacahe with capacity 5, put 2 string in it. it tells me maxMemory is 5242880 and memorySize is 2, so what is the unit of maxMemory and memorySize?

**Comment by adam0806** [comment]
> i create a lruCacahe with capacity 5, put 2 string in it. it tells me maxMemory is 5242880 and memorySize is 2, so what is the unit of maxMemory and memorySize?

You should define your getValueSize()

**Comment by hotchemi** [comment]
Sorry for the late but the library is not a production ready. Please use more popular one.
